apiVersion: v1
kind: Service
metadata:
  name: wordpress-redis
  labels: 
    app: wordpress
spec:
  selector:
    app: wordpress
    tier: redis
  clusterIP: None
  ports:
    - port: 6379
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-redis
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: redis
    spec:
      containers:
      - name: redis
        image: k8s.gcr.io/redis:e2e  # or just image: redis
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        ports:
        - containerPort: 6379
          name: redis